%% 根据waypoints画图
function h = draw_waypoints(P,h,id)
    if nargin == 1
        h = figure; id = 1;
    end
    color_array = {'#A2142F','#0072BD','#77AC30',...
                   '#7E2F8E','#EDB120','#D95319'};
    if id > length(color_array)
        id = mod(id,length(color_array));
    end
    waypoints = P.waypoints;
    % reference pn,pe,pd
    pe_ref = waypoints(:,1);
    pn_ref = waypoints(:,2);
    pz_ref = waypoints(:,3);
    
    figure(h);
    hold on;box on;grid on;
    % drawing the waypoints of dubins trajectory
    num_trajectory_points = length(pn_ref);
    % draw the trajectory
    num_draw_points = 10;
    trajectory_index_array = round(linspace(1,num_trajectory_points,...
                                            num_draw_points));
    draw_flag = 1; % 1:横坐标：Lon，纵坐标：Lat； 0：横坐标：Lat，纵坐标：Lon
    % plot the reference waypoints
    if draw_flag
        plot3(pn_ref,pe_ref,pz_ref,...
              'LineWidth',0.75,'Color',color_array{id},...
              'LineStyle','--',...
              'DisplayName','Reference waypoints');
        plot3(pn_ref(trajectory_index_array),...
              pe_ref(trajectory_index_array),...
              pz_ref(trajectory_index_array),...
              'LineStyle','none' ,'Color',color_array{id},...
              'Marker','x',...
              'DisplayName','Reference waypoints');
    else
        plot3(pe_ref,pn_ref,pz_ref,...
              'LineWidth',0.75,'Color',color_array{id},...
              'LineStyle','--',...
              'DisplayName','Reference waypoints');
        plot3(pe_ref(trajectory_index_array),...
              pn_ref(trajectory_index_array),...
              pz_ref(trajectory_index_array),...
              'LineStyle','none' ,'Color',color_array{id},...
              'Marker','x',...
              'DisplayName','Reference waypoints');
    end
end